kind: pipeline
type: docker
name: CI

trigger:
    branch :
        - master 
    event:
        include :
            - pull_request 
        exclude :
            - push

steps:
    - name : build
      image : mcr.microsoft.com/dotnet/sdk:8.0
      commands: 
       - cd Sources
       - dotnet restore MySolution.sln
       - dotnet build MySolution.sln -c Release --no-restore
    
    - name : tests
      image : mcr.microsoft.com/dotnet/sdk:8.0
      commands :
        - dotnet test
      depend_on : [ build ]