kind: pipeline
type: docker
name: CI

trigger:
    branch :
        - master 
    event:
        - pull_request 

steps:
    
    - name : buildCs
      image : mcr.microsoft.com/dotnet/sdk:8.0
      commands: 
       - cd Sources 
       - dotnet restore QuoridorCS.sln
       - dotnet build QuoridorCS.sln -c Release  --no-restore
       - dotnet publish QuoridorCS.sln -c Release  --no-restore -o $CI_PROJECT_DIR/build/release 

    - name: CsTests
      image: mcr.microsoft.com/dotnet/sdk:8.0
      commands:
      - cd Sources/
      - dotnet restore QuoridorCS.sln
      - dotnet test QuoridorCS.sln --no-restore
      depends_on: [buildCs]
    
    - name : buildMAUI
      image : hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dotnet8-maui
      commands :
      - cd Sources 
      - dotnet restore QuoridorMAUI.sln
      - dotnet build QuoridorMAUI.sln -c Release  --no-restore /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT -property:Aapt2ToolPath=$ANDROID_SDK_ROOT/build-tools/33.0.0
      - dotnet publish QuoridorMaui/QuoridorMaui.csproj -c Release  --no-restore -o $CI_PROJECT_DIR/build/release -f:net8.0-android /p:AndroidSdkDirectory=/usr/lib/android-sdk
    
    - name : MauiTests
      image : hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dotnet8-maui
      commands :
      - cd Sources 
      - dotnet restore QuoridorMAUI.sln
      - dotnet build QuoridorMAUI.sln -c Release  --no-restore /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT -property:Aapt2ToolPath=$ANDROID_SDK_ROOT/build-tools/33.0.0
      - dotnet test QuoridorMaui/QuoridorMaui.csproj -c Release  --no-restore -o $CI_PROJECT_DIR/build/release -f:net8.0-android /p:AndroidSdkDirectory=/usr/lib/android-sdk
      depends_on: [buildMAUI]

    - name: generate-and-deploy-docs
      image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-docdeployer
      failure: ignore
      volumes:
      - name: docs
        path: /docs
      commands:
        - /entrypoint.sh
      environement :
        NODOXYGEN : true
      when:
        branch:
          - master
        event:
          - push
          - pull_request
      depends_on: [buildCs,CsTests]    


    - name: code-inspection
      image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dronesonarplugin-dotnet8-maui
      environment:
        sonar_host: https://codefirst.iut.uca.fr/sonar/
        sonar_token:
          from_secret: SECRET_SONAR_LOGIN
          project_key: QuoridorSae201
      commands:
      - cd Sources/
      - dotnet restore Quoridor.sln
      - dotnet sonarscanner begin /k:Quoridor /d:sonar.host.url=https://codefirst.iut.uca.fr/sonar/ /d:sonar.coverageReportPaths="coveragereport/SonarQube.xml" /d:sonar.login=$sonar_token /d:sonar.verbose=true
      - dotnet build  Quoridor.sln -c Release --no-restore /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT -property:Aapt2ToolPath=$ANDROID_SDK_ROOT/build-tools/34.0.0
      - dotnet test Quoridor.sln --no-restore --collect "XPlat Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT -property:Aapt2ToolPath=$ANDROID_SDK_ROOT/build-tools/34.0.0
      - reportgenerator -reports:"**/coverage.cobertura.xml" -reporttypes:SonarQube -targetdir:"coveragereport"
      - dotnet publish Sources/Quoridor.csproj -c Release --no-restore -o $CI_PROJECT_DIR/build/release -f:net8.0-android /p:AndroidSdkDirectory=/usr/lib/android-sdk
      - dotnet sonarscanner end /d:sonar.login=$sonar_token
      