kind: pipeline
type: docker
name: CI

trigger:
    branch :
        - master 
    event:
        - pull_request 

steps:
    - name : build
      image :  mcr.microsoft.com/dotnet/sdk:8.0
      commands: 
       - cd Sources
       - dotnet restore MySolution.sln
       - dotnet build MySolution.sln -c Debug --no-restore
       - dotnet publish MySolution.sln -c Debug --no-restore -o $CI_PROJECT_DIR/build/debug
    
    