kind: pipeline
type: docker
name: CI

trigger:
    branch :
        - master 
    event:
        - pull_request 

steps:
    
    - name : buildCs
      image : mcr.microsoft.com/dotnet/sdk:9.0
      commands: 
       - cd Sources 
       - dotnet restore QuoridorCS.sln
       - dotnet build QuoridorCS.sln -c Release  --no-restore
       - dotnet publish QuoridorCS.sln -c Release  --no-restore -o $CI_PROJECT_DIR/build/release 

    - name: CsTests
      image: mcr.microsoft.com/dotnet/sdk:9.0
      commands:
      - cd Sources/
      - dotnet restore QuoridorCS.sln
      - dotnet test QuoridorCS.sln --no-restore
      depends_on: [buildCs]
    
    - name : buildMAUI
      image : hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dotnet9-maui
      commands :
      - cd Sources 
      - dotnet restore QuoridorMAUI.sln
      - dotnet build QuoridorMAUI.sln -c Release --no-restore /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT /p:AndroidSdkVersion=33.0.0 /p:AndroidTargetSdkVersion=33 /p:AndroidMinSdkVersion=21 /p:AndroidUseLatestPlatformSdk=false
      - dotnet publish QuoridorMaui/QuoridorMaui.csproj -c Release --no-restore -o $CI_PROJECT_DIR/build/release -f:net9.0-android /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT /p:AndroidSdkVersion=33.0.0 /p:AndroidTargetSdkVersion=33 /p:AndroidMinSdkVersion=21 /p:AndroidUseLatestPlatformSdk=false
    
    - name : MauiTests
      image : hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dotnet9-maui
      commands :
      - cd Sources 
      - dotnet restore QuoridorMAUI.sln
      - dotnet build QuoridorMAUI.sln -c Release --no-restore /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT /p:AndroidSdkVersion=33.0.0 /p:AndroidTargetSdkVersion=33 /p:AndroidMinSdkVersion=21 /p:AndroidUseLatestPlatformSdk=false
      - dotnet test QuoridorMaui/QuoridorMaui.csproj -c Release --no-restore -o $CI_PROJECT_DIR/build/release -f:net9.0-android /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT /p:AndroidSdkVersion=33.0.0 /p:AndroidTargetSdkVersion=33 /p:AndroidMinSdkVersion=21 /p:AndroidUseLatestPlatformSdk=false
      depends_on: [buildMAUI]

    - name: generate-and-deploy-docs
      image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-docdeployer
      volumes:
        - name: docs
          path: /docs
      commands:
        - pwd 
        - ls
        - ls Documentation
        - ls Documentation/doxygen
        - /entrypoint.sh
      when:
          branch:
            - master
          event:
            - push
            - pull_request
      depends_on: [CsTests]    

    - name: code-inspection
      image: mcr.microsoft.com/dotnet/sdk:9.0
      environment:
        sonar_host: https://codefirst.iut.uca.fr/sonar/
        sonar_token:
          from_secret: SONAR_TOKEN
        project_key: QuoridorSae201
      commands:
        - apt-get update
        - apt-get install -y gnupg2
        - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9 6ED0E7B82643E131
        - apt-get update && apt-get install -y openjdk-17-jdk
        - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        - export PATH=$JAVA_HOME/bin:$PATH
        - java -version
        - dotnet tool install --global dotnet-sonarscanner
        - dotnet tool install --global dotnet-reportgenerator-globaltool 
        - export PATH="$PATH:/root/.dotnet/tools"
        - cd Sources/
        - dotnet restore QuoridorCS.sln
        - dotnet sonarscanner begin /k:QuoridorSae201 /d:sonar.host.url=https://codefirst.iut.uca.fr/sonar/ /d:sonar.coverageReportPaths="coveragereport/SonarQube.xml" /d:sonar.login=$${sonar_token} /d:sonar.verbose=true
        - dotnet build QuoridorCS.sln -c Release  --no-restore
        - dotnet test QuoridorCS.sln --no-restore --collect:"XPlat Code Coverage" --results-directory TestResults
        - reportgenerator -reports:"**/coverage.cobertura.xml" -reporttypes:SonarQube -targetdir:"coveragereport"
        - dotnet publish QuoridorCS.sln -c Release  --no-restore -o $CI_PROJECT_DIR/build/release 
        - dotnet sonarscanner end /d:sonar.login=$${sonar_token}
      depends_on: [CsTests]