kind: pipeline
type: docker
name: CI

trigger:
    branch :
        - master 
    event:
        - pull_request 

steps:
    - name : build
      image : hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dotnet8-maui
      commands: 
       - cd Sources
       - dotnet restore MySolution.sln
       - dotnet build MySolution.sln -c Debug --no-restore
       - dotnet publish MySolution.sln -c Debug --no-restore -o $CI_PROJECT_DIR/build/debug
    
    