@startuml Quoridor Class Diagram

' Interfaces
interface IGameManager {
    +InitGame(Player player1, Player player2)
    +LoadGame(): Game
    +PlayTurn()
    +IsGameFinished(): bool
}

interface ISaveManager {
    +SaveGame(Game game)
}

interface ILoadManager {
    +LoadGame(Game game): Game
}

' Classes principales
class GameManager {
    -loadManager: ILoadManager
    -saveManager: ISaveManager
    -game: Game
    +InitGame(Player player1, Player player2)
    +LoadGame(): Game
    +PlayTurn()
    +IsGameFinished(): bool
}

class Game {
    -players: List<Player>
    -bestOf: BestOf
    -currentRound: Round
    -isGameOver: bool
    +LaunchRound()
    +EndGame()
    +GetCurrentPlayer(): Player
    +GetPlayers(): List<Player>
    +GetBestOf(): BestOf
    +IsGameOver(): bool
}

class Round {
    -board: Board
    -currentPlayer: Player
    +SwitchCurrentPlayer(Player player)
    +MovePawn(int newX, int newY)
    +PlacingWall(int x, int y, string orientation): bool
}

class Board {
    -walls: List<Wall>
    -pawns: List<Pawn>
    +MovePawn(string playerName, Position position)
    +IsWallONBoard(int x, int y, string orientation): bool
    +AddCoupleWall(Wall wall1, Wall wall2)
}

class BestOf {
    -player1Score: int
    -player2Score: int
    -numberOfGames: int
    +AddPlayer1Victory()
    +AddPlayer2Victory()
    +GetPlayer1Score(): int
    +GetPlayer2Score(): int
    +GetNumberOfGames(): int
}

class Player {
    -name: string
    -victories: uint
    +Name { get; }
    +Victories { get; }
    +AddVictory()
}

class Wall {
    -position1: Position
    -position2: Position
    +SetSecondPosition(Position position)
    +GetSecondPosition(): Position
    +SetSecondPosition(int x, int y)
    +IsPlaceable(): bool
}

class Pawn {
    -position: Position
    +Move()
    +GetPawnPosition(): Position
    +Move(Position position)
}

class Position {
    -X: int
    -Y: int
    +SetPosition(int x, int y)
    +GetPosition(): Position
    +GetPositionX(): int
    +GetPositionY(): int
}

' Relations
GameManager ..|> IGameManager
GameManager --> ILoadManager
GameManager --> ISaveManager
GameManager --> Game

Game --> BestOf
Game --> "1..*" Player
Game --> Round

Round --> Board
Round --> Player

Board --> "*" Wall
Board --> "*" Pawn

Wall *--> Position
Pawn *--> Position

@enduml 